Improve handling of binder auto profile swapping.
JTensai/binder pull request #4
Opened 2021-03-10 19:07 UTC by alexanderkershaw

Hi,

I've been wanting this feature for a while. Decided to just have a go adding it, was very simple in the end. Maybe you want to incorporate it to the addon. 

Basically just makes the automatically Load_Profile on spec swap look for a profile called <class>-<spec> rather than just <spec>. Fixes the problem if you play two identically named specs like holy priest/pala or resto druid/shaman but want to have seperate keybindings for each. 

Thanks,
Alex

2021-03-28 07:13 UTC, JTensai commented
Thanks for taking the time to create a pull request! Its great to have another pair of eyes look at this code :D

I'll merge this in if you can make it backwards compatible with people who are using the system as it already is.

Maybe run a check to see if there are any matching specs for class-specialization and if not, try to just load one for the specialization. That way people can be more specific if they want to.

Hope to see an update sometime!

2021-03-28 07:14 UTC, JTensai requested changes
See comment in conversation.

2021-03-28 15:17 UTC, alexanderkershaw commented
Made changes to be backwards compatible. Also includes a slight improvement to the existing behaviour - no longer attempts to load a profile that doesn't exist, rather than always trying to load a "spec" profile on respec event.

2021-03-29 01:53 UTC, JTensai approved these changes

2021-03-29 01:54 UTC, JTensai commented
Looks great! Thanks for the update.

2021-03-29 01:54 UTC, merged

2021-03-30 18:46 UTC, aza547 commented
Very welcome!